swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /addresses/:
    get:
      tags:
      - addresses
      description: get Addresses
      operationId: AddressesController.Get All
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Addresses'
        "403":
          description: ""
    post:
      tags:
      - addresses
      description: create Addresses
      operationId: AddressesController.Post
      parameters:
      - in: body
        name: body
        description: body for Addresses content
        required: true
        schema:
          $ref: '#/definitions/models.Addresses'
      responses:
        "201":
          description: '{int} models.Addresses'
        "403":
          description: body is empty
  /addresses/{id}:
    get:
      tags:
      - addresses
      description: get Addresses by id
      operationId: AddressesController.Get One
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Addresses'
        "403":
          description: :id is empty
    put:
      tags:
      - addresses
      description: update the Addresses
      operationId: AddressesController.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for Addresses content
        required: true
        schema:
          $ref: '#/definitions/models.Addresses'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Addresses'
        "403":
          description: :id is not int
    delete:
      tags:
      - addresses
      description: delete the Addresses
      operationId: AddressesController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "403":
          description: id is empty
  /persons/:
    get:
      tags:
      - persons
      description: get Persons
      operationId: PersonsController.Get All
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Persons'
        "403":
          description: ""
    post:
      tags:
      - persons
      description: create Persons
      operationId: PersonsController.Post
      parameters:
      - in: body
        name: body
        description: body for Persons content
        required: true
        schema:
          $ref: '#/definitions/models.Persons'
      responses:
        "201":
          description: '{int} models.Persons'
        "403":
          description: body is empty
  /persons/{id}:
    get:
      tags:
      - persons
      description: get Persons by id
      operationId: PersonsController.Get One
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Persons'
        "403":
          description: :id is empty
    put:
      tags:
      - persons
      description: update the Persons
      operationId: PersonsController.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for Persons content
        required: true
        schema:
          $ref: '#/definitions/models.Persons'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Persons'
        "403":
          description: :id is not int
    delete:
      tags:
      - persons
      description: delete the Persons
      operationId: PersonsController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "403":
          description: id is empty
definitions:
  models.Addresses:
    title: Addresses
    type: object
    properties:
      Id:
        type: integer
        format: int64
      PersonsId:
        $ref: '#/definitions/models.Persons'
      StreetCity:
        type: string
      StreetName:
        type: string
  models.Persons:
    title: Persons
    type: object
    properties:
      Firstname:
        type: string
      Id:
        type: integer
        format: int64
      Lastname:
        type: string
      ZipCode:
        type: integer
        format: int64
tags:
- name: addresses
  description: |
    AddressesController operations for Addresses
- name: persons
  description: |
    PersonsController operations for Persons
